# Generated by Django 3.2.8 on 2021-10-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(to='bot.Ingredient'),
        ),
    ]
